version: "3.2"

services:
  traefik:
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.api.address=:8082"
      - "--entrypoints.notebook.address=:8888"
      - "--entrypoints.dash.address=:8050"
      - "--entrypoints.whoami.address=:8055"
    ports:
      - "8088:8080" # traefik

  app:
    volumes:
      - .env:/app/.env
      - ./var:/app/var
      - ./notebooks:/app/notebooks
      - ./cataclop:/app/cataclop
      - ./dash:/app/dash
      - ./docker/ipython_config.py:/root/.ipython/profile_default/ipython_config.py
      - ./docker/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./docker/docker-entrypoint.sh:/docker-entrypoint.sh
