[tool.poetry]
name = "poetry-demo"
version = "0.1.0"
description = ""
authors = ["Sébastien Eustace <sebastien@eustace.io>"]

[tool.poetry.dependencies]
python = "3.7.*"
django-environ = "*"
django = "*"
djangorestframework = "*"
mysqlclient = "*"
django-configurations = "*"
pytz = "*"
jupyter = "*"
bencode = "*"
pandas = "*"
scikit-learn = "==0.20.2"
scipy = "*"
django-extensions = "*"
tables = "*"
matplotlib = "*"
certifi = "*"
fastparquet = "*"
jinja2 = "*"
requests = "*"
pyopenssl = "*"
idna = "*"
sentry-sdk = "==0.5.5"
joblib = "*"
xgboost = "~=0.9"
seaborn = "*"
theano = "*"
scikit-optimize = "*"
gunicorn = "*"
djangorestframework-simplejwt = "*"
django-filter = "*"
trueskill = "*"
django-cursor-pagination = "*"
dill = "*"
django-redis = "*"
faker = "*"
factory-boy = "*"
jupyterlab = "*"
tqdm = "*"
uwsgi = "*"
dash = "==1.19.0"
python-dateutil = "*"
celery = "*"
keras = "*"
tensorflow = "==2.4.1"

[tool.poetry.dev-dependencies]
django-debug-toolbar = "*"
django-debug-toolbar-request-history = "*"