# Generated by Django 2.0.4 on 2018-04-27 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='racesession',
            name='hippodrome',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Hippodrome'),
            preserve_default=False,
        ),
    ]
