# Generated by Django 2.0.4 on 2018-04-28 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_racesession_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hippodrome',
            old_name='short_name',
            new_name='code',
        ),
        migrations.AddField(
            model_name='race',
            name='num',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.RaceSession'),
            preserve_default=False,
        ),
    ]
