# Generated by Django 2.0.4 on 2018-04-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180428_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horse',
            old_name='race',
            new_name='breed',
        ),
        migrations.AlterField(
            model_name='horse',
            name='sex',
            field=models.CharField(max_length=20),
        ),
    ]
