# Generated by Django 2.0.4 on 2018-04-28 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180428_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='herder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Herder'),
        ),
        migrations.AlterField(
            model_name='player',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Owner'),
        ),
    ]
