# Generated by Django 2.0.4 on 2018-05-02 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180428_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('evolution', models.FloatField()),
                ('date', models.DateTimeField()),
                ('is_final', models.BooleanField(default=False)),
                ('is_final_ref', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='horse',
            name='father',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='mother',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='mother_father',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='earnings',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='handicap_distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='handicap_weight',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='is_first_timer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_racing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='placed_2_count',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='placed_3_count',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='placed_count',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='placed_earnings',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='prev_year_earnings',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='race_count',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='victory_count',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='victory_earnings',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='year_earnings',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='category',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='condition_age',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='condition_sex',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='delcared_player_count',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='distance',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='num_bis',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='prize',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='race',
            name='sub_category',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='odds',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player'),
        ),
    ]
