# Generated by Django 2.0.4 on 2018-05-02 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180502_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='delcared_player_count',
            new_name='declared_player_count',
        ),
    ]
