# Generated by Django 2.0.4 on 2018-05-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180502_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='herder',
            name='imported_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hippodrome',
            name='imported_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='horse',
            name='imported_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jockey',
            name='imported_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='odds',
            name='imported_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='imported_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='player',
            name='imported_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='race',
            name='imported_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='racesession',
            name='imported_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='imported_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
