# Generated by Django 2.0.5 on 2018-05-19 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180502_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('combo', models.TextField()),
                ('dividend', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Race')),
            ],
        ),
        migrations.AlterModelOptions(
            name='odds',
            options={'verbose_name_plural': 'odds'},
        ),
        migrations.AddField(
            model_name='player',
            name='placed_dividend',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='winner_dividend',
            field=models.IntegerField(null=True),
        ),
    ]
