# Generated by Django 2.0.5 on 2018-05-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_player_final_odds_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='num',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
    ]
