# Generated by Django 2.0.5 on 2018-05-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_player_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='final_odds',
            field=models.FloatField(null=True),
        ),
    ]
