# Generated by Django 2.1.3 on 2018-12-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_player_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herder',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hippodrome',
            name='code',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='hippodrome',
            name='country',
            field=models.CharField(db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='horse',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jockey',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='num',
            field=models.SmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='num',
            field=models.SmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='start_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='racesession',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='racesession',
            name='num',
            field=models.SmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
