# Generated by Django 2.1.4 on 2019-01-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20181215_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='final_odds_offline',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='final_odds_ref_offline',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='placed_dividend_offline',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='winner_dividend_offline',
            field=models.IntegerField(null=True),
        ),
    ]
