# Generated by Django 2.1.4 on 2019-02-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20190117_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='odds',
            name='offline',
            field=models.BooleanField(default=False),
        ),
    ]
