# Generated by Django 2.1.4 on 2019-02-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_odds_offline'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='final_odds_ref_unibet',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='final_odds_unibet',
            field=models.FloatField(null=True),
        ),
    ]
