# Generated by Django 3.0.6 on 2020-06-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190206_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='herder_avg_winning_dividend',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='herder_winning_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='jockey_avg_winning_dividend',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='jockey_winning_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='trainer_avg_winning_dividend',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='trainer_winning_rate',
            field=models.FloatField(null=True),
        ),
    ]
