# Generated by Django 3.0.7 on 2020-06-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200603_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hist_1_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='hist_2_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='hist_3_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='jockey_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='trueskill_mu',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='trueskill_sigma',
            field=models.FloatField(null=True),
        ),
    ]
