# Generated by Django 3.0.8 on 2021-01-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_player_position_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='odds',
            name='whale',
            field=models.BooleanField(default=False),
        ),
    ]
