# Generated by Django 3.2.8 on 2021-10-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20211002_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betresult',
            name='combo',
            field=models.JSONField(),
        ),
    ]
