# Generated by Django 2.1.4 on 2019-01-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='program',
            field=models.TextField(null=True),
        ),
    ]
