# Generated by Django 3.0.7 on 2020-06-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmu', '0002_bet_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='provider',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='stats_bet_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='stats_prediction_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='stats_scrap_time',
            field=models.IntegerField(null=True),
        ),
    ]
