# Generated by Django 3.2.7 on 2021-10-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmu', '0003_auto_20200612_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
